version: '3.8'

services:
  andera-base-worker:
    image: andera-top/base-worker
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AUTH_KEY=${AUTH_KEY}
      - LB_AUTH_KEY=${LB_AUTH_KEY}
      - PORT=${PORT}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - GROUP=${GROUP}
      - CONTRACT=${CONTRACT}
      - SLOTS=${SLOTS}
      - DEFAULT_TIMEOUT=${DEFAULT_TIMEOUT}
      - LOG_LEVEL=${LOG_LEVEL}
      - MAX_LOGS=${MAX_LOGS}
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT}
      - WEBHOOK_MAX_RETRIES=${WEBHOOK_MAX_RETRIES}
      - WEBHOOK_RETRY_DELAY=${WEBHOOK_RETRY_DELAY}
      - WEBHOOK_HEADERS=${WEBHOOK_HEADERS}
      - OPENAPI_ENABLED=${OPENAPI_ENABLED}
    ports:
      - "${PORT}:${PORT}"
    command: node dist/app.js
    volumes:
      - ./workers.json:/app/workers.json